const SOURCE = "NEB recognition-specificity list; REBASE database literature";

export const restrictionEnzymeRecords = [
  { id: "aatii", name: "AatII", recognition: "GACGTC", cutTop: 5, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "acc65i", name: "Acc65I", recognition: "GGTACC", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "acci", name: "AccI", recognition: "GTMKAC", cutTop: 2, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "acli", name: "AclI", recognition: "AACGTT", cutTop: 2, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "afei", name: "AfeI", recognition: "AGCGCT", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "aflii", name: "AflII", recognition: "CTTAAG", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "afliii", name: "AflIII", recognition: "ACRYGT", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "agei", name: "AgeI", recognition: "ACCGGT", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "alui", name: "AluI", recognition: "AGCT", cutTop: 2, cutBottom: 2, overhang: "blunt", source: SOURCE },
  { id: "apai", name: "ApaI", recognition: "GGGCCC", cutTop: 5, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "apoi", name: "ApoI", recognition: "RAATTY", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "asci", name: "AscI", recognition: "GGCGCGCC", cutTop: 2, cutBottom: 6, overhang: "5 prime", source: SOURCE },
  { id: "asei", name: "AseI", recognition: "ATTAAT", cutTop: 2, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "asisi", name: "AsiSI", recognition: "GCGATCGC", cutTop: 5, cutBottom: 3, overhang: "3 prime", source: SOURCE },
  { id: "avai", name: "AvaI", recognition: "CYCGRG", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "avaii", name: "AvaII", recognition: "GGWCC", cutTop: 1, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "avrii", name: "AvrII", recognition: "CCTAGG", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "bamhi", name: "BamHI", recognition: "GGATCC", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "bani", name: "BanI", recognition: "GGYRCC", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "banii", name: "BanII", recognition: "GRGCYC", cutTop: 5, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "bcli", name: "BclI", recognition: "TGATCA", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "bfai", name: "BfaI", recognition: "CTAG", cutTop: 1, cutBottom: 3, overhang: "5 prime", source: SOURCE },
  { id: "bglii", name: "BglII", recognition: "AGATCT", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "blpi", name: "BlpI", recognition: "GCTNAGC", cutTop: 2, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "bmti", name: "BmtI", recognition: "GCTAGC", cutTop: 5, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "bsaai", name: "BsaAI", recognition: "YACGTR", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "bsahi", name: "BsaHI", recognition: "GRCGYC", cutTop: 2, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "bsiei", name: "BsiEI", recognition: "CGRYCG", cutTop: 4, cutBottom: 2, overhang: "3 prime", source: SOURCE },
  { id: "bsiwi", name: "BsiWI", recognition: "CGTACG", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "bsp1286i", name: "Bsp1286I", recognition: "GDGCHC", cutTop: 5, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "bspei", name: "BspEI", recognition: "TCCGGA", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "bsphi", name: "BspHI", recognition: "TCATGA", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "bsrfi", name: "BsrFI", recognition: "RCCGGY", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "bsrgi", name: "BsrGI", recognition: "TGTACA", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "bsshii", name: "BssHII", recognition: "GCGCGC", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "bstbi", name: "BstBI", recognition: "TTCGAA", cutTop: 2, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "bsteii", name: "BstEII", recognition: "GGTNACC", cutTop: 1, cutBottom: 6, overhang: "5 prime", source: SOURCE },
  { id: "bstni", name: "BstNI", recognition: "CCWGG", cutTop: 2, cutBottom: 3, overhang: "5 prime", source: SOURCE },
  { id: "bstui", name: "BstUI", recognition: "CGCG", cutTop: 2, cutBottom: 2, overhang: "blunt", source: SOURCE },
  { id: "cac8i", name: "Cac8I", recognition: "GCNNGC", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "clai", name: "ClaI", recognition: "ATCGAT", cutTop: 2, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "ddei", name: "DdeI", recognition: "CTNAG", cutTop: 1, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "drai", name: "DraI", recognition: "TTTAAA", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "eaei", name: "EaeI", recognition: "YGGCCR", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "eagi", name: "EagI", recognition: "CGGCCG", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "eco53ki", name: "Eco53kI", recognition: "GAGCTC", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "ecori", name: "EcoRI", recognition: "GAATTC", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "ecorv", name: "EcoRV", recognition: "GATATC", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "fnu4hi", name: "Fnu4HI", recognition: "GCNGC", cutTop: 2, cutBottom: 3, overhang: "5 prime", source: SOURCE },
  { id: "fsei", name: "FseI", recognition: "GGCCGGCC", cutTop: 6, cutBottom: 2, overhang: "3 prime", source: SOURCE },
  { id: "fspi", name: "FspI", recognition: "TGCGCA", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "haeiii", name: "HaeIII", recognition: "GGCC", cutTop: 2, cutBottom: 2, overhang: "blunt", source: SOURCE },
  { id: "hhai", name: "HhaI", recognition: "GCGC", cutTop: 3, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "hincii", name: "HincII", recognition: "GTYRAC", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "hindiii", name: "HindIII", recognition: "AAGCTT", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "hinfi", name: "HinfI", recognition: "GANTC", cutTop: 1, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "hinp1i", name: "HinP1I", recognition: "GCGC", cutTop: 1, cutBottom: 3, overhang: "5 prime", source: SOURCE },
  { id: "hpai", name: "HpaI", recognition: "GTTAAC", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "hpaii", name: "HpaII", recognition: "CCGG", cutTop: 1, cutBottom: 3, overhang: "5 prime", source: SOURCE },
  { id: "kasi", name: "KasI", recognition: "GGCGCC", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "kpni", name: "KpnI", recognition: "GGTACC", cutTop: 5, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "mfei", name: "MfeI", recognition: "CAATTG", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "mlui", name: "MluI", recognition: "ACGCGT", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "msci", name: "MscI", recognition: "TGGCCA", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "msei", name: "MseI", recognition: "TTAA", cutTop: 1, cutBottom: 3, overhang: "5 prime", source: SOURCE },
  { id: "mspi", name: "MspI", recognition: "CCGG", cutTop: 1, cutBottom: 3, overhang: "5 prime", source: SOURCE },
  { id: "naei", name: "NaeI", recognition: "GCCGGC", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "nari", name: "NarI", recognition: "GGCGCC", cutTop: 2, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "ncoi", name: "NcoI", recognition: "CCATGG", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "ndei", name: "NdeI", recognition: "CATATG", cutTop: 2, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "ngomiv", name: "NgoMIV", recognition: "GCCGGC", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "nhei", name: "NheI", recognition: "GCTAGC", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "noti", name: "NotI", recognition: "GCGGCCGC", cutTop: 2, cutBottom: 6, overhang: "5 prime", source: SOURCE },
  { id: "nrui", name: "NruI", recognition: "TCGCGA", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "nsii", name: "NsiI", recognition: "ATGCAT", cutTop: 5, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "nspi", name: "NspI", recognition: "RCATGY", cutTop: 5, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "paci", name: "PacI", recognition: "TTAATTAA", cutTop: 5, cutBottom: 3, overhang: "3 prime", source: SOURCE },
  { id: "pcii", name: "PciI", recognition: "ACATGT", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "pmei", name: "PmeI", recognition: "GTTTAAAC", cutTop: 4, cutBottom: 4, overhang: "blunt", source: SOURCE },
  { id: "pmli", name: "PmlI", recognition: "CACGTG", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "psii", name: "PsiI", recognition: "TTATAA", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "pspomi", name: "PspOMI", recognition: "GGGCCC", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "psti", name: "PstI", recognition: "CTGCAG", cutTop: 5, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "pvui", name: "PvuI", recognition: "CGATCG", cutTop: 4, cutBottom: 2, overhang: "3 prime", source: SOURCE },
  { id: "pvuii", name: "PvuII", recognition: "CAGCTG", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "rsai", name: "RsaI", recognition: "GTAC", cutTop: 2, cutBottom: 2, overhang: "blunt", source: SOURCE },
  { id: "rsrii", name: "RsrII", recognition: "CGGWCCG", cutTop: 2, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "saci", name: "SacI", recognition: "GAGCTC", cutTop: 5, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "sacii", name: "SacII", recognition: "CCGCGG", cutTop: 4, cutBottom: 2, overhang: "3 prime", source: SOURCE },
  { id: "sali", name: "SalI", recognition: "GTCGAC", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "sau3ai", name: "Sau3AI", recognition: "GATC", cutTop: 0, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "sbfi", name: "SbfI", recognition: "CCTGCAGG", cutTop: 6, cutBottom: 2, overhang: "3 prime", source: SOURCE },
  { id: "scai", name: "ScaI", recognition: "AGTACT", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "sexai", name: "SexAI", recognition: "ACCWGGT", cutTop: 1, cutBottom: 6, overhang: "5 prime", source: SOURCE },
  { id: "sfoi", name: "SfoI", recognition: "GGCGCC", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "smai", name: "SmaI", recognition: "CCCGGG", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "snabi", name: "SnaBI", recognition: "TACGTA", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "spei", name: "SpeI", recognition: "ACTAGT", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "sphi", name: "SphI", recognition: "GCATGC", cutTop: 5, cutBottom: 1, overhang: "3 prime", source: SOURCE },
  { id: "srfi", name: "SrfI", recognition: "GCCCGGGC", cutTop: 4, cutBottom: 4, overhang: "blunt", source: SOURCE },
  { id: "sspi", name: "SspI", recognition: "AATATT", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "stui", name: "StuI", recognition: "AGGCCT", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE },
  { id: "styi", name: "StyI", recognition: "CCWWGG", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "taqi", name: "TaqI", recognition: "TCGA", cutTop: 1, cutBottom: 3, overhang: "5 prime", source: SOURCE },
  { id: "tfii", name: "TfiI", recognition: "GAWTC", cutTop: 1, cutBottom: 4, overhang: "5 prime", source: SOURCE },
  { id: "xbai", name: "XbaI", recognition: "TCTAGA", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "xhoi", name: "XhoI", recognition: "CTCGAG", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "xmai", name: "XmaI", recognition: "CCCGGG", cutTop: 1, cutBottom: 5, overhang: "5 prime", source: SOURCE },
  { id: "xmni", name: "XmnI", recognition: "GAANNNNTTC", cutTop: 5, cutBottom: 5, overhang: "blunt", source: SOURCE },
  { id: "zrai", name: "ZraI", recognition: "GACGTC", cutTop: 3, cutBottom: 3, overhang: "blunt", source: SOURCE }
];
